services:
  - type: web
    name: TL_Music_Viewer
    runtime: node
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
